title: Все об Arch Linux
name: Alexey Boyko
description: Установка и настройка Arch Linux, статьи, конфиги, группа поддержки. 
url: "https://ordanax.github.io/"
baseurl: "/"
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
