---
title: Все об Arch Linux
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
description: Arch Linux будет тем, что вы из него сделаете!
baseurl: ''
url: https://ordanax.github.io
permalink: "/:title"
markdown: kramdown
gems:
- jekyll-paginate
- jekyll-sitemap
- jekyll-feed
paginate: 7
exclude:
- Gemfile
- Gemfile.lock

soc:
  <li><a href="https://vk.com/arch4u"><i class="fab fa-vk"></i></a></li>
  <li><a href="https://www.youtube.com/Arch4u"><i class="fab fa-youtube"></i></a></li>
  <li><a href="/feed.xml"><i class="fas fa-rss"></i></a></li>
