---
title: Все об Arch Linux
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
description: Установка и настройка Arch Linux, статьи, конфиги, группа поддержки.
baseurl: 'blog'
url: https://ordanax.github.io
permalink: "/:title"
markdown: kramdown

plugins:
- jekyll-paginate-v2
- jekyll-feed

category_dir: "/"
pagination:
  enabled: true
  paginate: 6
  title: ":title - Страница :num"
  limit: 0
  sort_field: "date"
  sort_reverse: true
  trail:
    before: 2
    after: 2
    
exclude: ['Gemfile','Gemfile.lock','node_modules', 'gulpfile.js', 'package.json', 'package-lock.json', 'js/common.js', 'npm-debug.log', '**/Thumbs.db', 'libs', 'sass', '**/*.DS_Store']

soc:
  <li><a href="https://vk.com/arch4u"><i class="fab fa-vk"></i></a></li>
  <li><a href="https://www.youtube.com/Arch4u"><i class="fab fa-youtube"></i></a></li>
  <li><a href="/feed.xml"><i class="fas fa-rss"></i></a></li>



