---
title: Все об Arch Linux
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
description: Установка и настройка Arch Linux, статьи, конфиги, группа поддержки.
baseurl: ''
url: https://ordanax.github.io
permalink: "/:title"
markdown: kramdown
gems:
- jekyll-paginate-v2
#- jekyll-sitemap
- jekyll-feed

plugins: [jekyll-paginate-v2]
category_dir: blog
pagination:
  enabled: true
  per_page: 9
  title: ':title - Страница :num'
  limit: 0
  sort_field: 'date'
  sort_reverse: true
  trail:
    before: 4
    after: 4

exclude:
- Gemfile
- Gemfile.lock
