---
title: Html Blog
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
email: mikhailyand@ya.ru
description: Блог программиста. Создание сайтов на php, html, а также с помощью популярных
  CMS.
baseurl: ''
url: https://htmlblog.github.io
permalink: "/:title"
markdown: kramdown
gems:
- jekyll-paginate
- jekyll-sitemap
- jekyll-feed
paginate: 7
exclude:
<<<<<<< HEAD
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME

baseurl: /
=======
- Gemfile
- Gemfile.lock
>>>>>>> 1e8c921584d047648064233f87d6702848016e09
